"""cyclone ledger alerts model runs

Revision ID: 04f1988023bf
Revises: d0708ec5c75a
Create Date: 2026-09-19 09:44:32.862407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f1988023bf'
down_revision: Union[str, Sequence[str], None] = 'd0708ec5c75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyclone_exposure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_name', sa.String(length=80), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('storm_day_prob', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('severe_day_prob', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('storms_per_year', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cyclone_exposure_port_name'), 'cyclone_exposure', ['port_name'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=20), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('order', sa.String(length=20), nullable=False),
    sa.Column('train_rows', sa.Integer(), nullable=False),
    sa.Column('train_end', sa.Date(), nullable=False),
    sa.Column('holdout_mape', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('drift_before', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_index_name'), 'model_runs', ['index_name'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('param_a', sa.String(length=60), nullable=True),
    sa.Column('param_b', sa.String(length=60), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('webhook_url', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fixture_date', sa.Date(), nullable=False),
    sa.Column('vessel_name', sa.String(length=120), nullable=False),
    sa.Column('origin_country', sa.String(length=60), nullable=False),
    sa.Column('destination_port', sa.String(length=80), nullable=False),
    sa.Column('cargo_tonnes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('charter_type', sa.String(length=20), nullable=False),
    sa.Column('rate_usd_per_tonne', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_entry_hash'), 'ledger_entries', ['entry_hash'], unique=False)
    op.create_index(op.f('ix_ledger_entries_fixture_date'), 'ledger_entries', ['fixture_date'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivery', sa.String(length=120), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_user_id'), 'alert_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_events_user_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_ledger_entries_fixture_date'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_hash'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_model_runs_index_name'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_cyclone_exposure_port_name'), table_name='cyclone_exposure')
    op.drop_table('cyclone_exposure')
    # ### end Alembic commands ###
