"""initial schema: ports, berths, vessels, routes, freight_rates, trade_volumes, fixtures, disruption_events, users

Revision ID: 8cc68f1273fe
Revises: 
Create Date: 2026-09-18 16:21:55.783735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc68f1273fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruption_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('source_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruption_events_start_date'), 'disruption_events', ['start_date'], unique=False)
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unlocode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('is_destination', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('max_draft_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_loa_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_beam_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tidal_restricted', sa.Boolean(), nullable=False),
    sa.Column('max_vessels_per_tide', sa.Integer(), nullable=True),
    sa.Column('annual_capacity_mtpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_turnaround_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unlocode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vessel_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('dwt_min', sa.Numeric(precision=9, scale=1), nullable=False),
    sa.Column('dwt_max', sa.Numeric(precision=9, scale=1), nullable=False),
    sa.Column('typical_loa_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('typical_beam_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('typical_draft_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('berths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('draft_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('loa_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('beam_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cargo_type', sa.String(length=60), nullable=True),
    sa.Column('handling_rate_tpd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_port_id', sa.Integer(), nullable=False),
    sa.Column('destination_port_id', sa.Integer(), nullable=False),
    sa.Column('distance_nm', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('typical_transit_days', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('primary_commodity', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('origin_country', sa.String(length=80), nullable=False),
    sa.Column('destination_port_id', sa.Integer(), nullable=True),
    sa.Column('commodity', sa.String(length=60), nullable=False),
    sa.Column('tonnes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imo', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vessel_class_id', sa.Integer(), nullable=False),
    sa.Column('dwt', sa.Numeric(precision=9, scale=1), nullable=True),
    sa.Column('loa_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('beam_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('draft_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('flag', sa.String(length=60), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vessel_class_id'], ['vessel_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_date', sa.Date(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('vessel_class_id', sa.Integer(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('charter_type', sa.String(length=20), nullable=False),
    sa.Column('cargo_tonnes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rate_unit', sa.String(length=20), nullable=True),
    sa.Column('laycan_start', sa.Date(), nullable=True),
    sa.Column('laycan_end', sa.Date(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vessel_class_id'], ['vessel_classes.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_fixture_date'), 'fixtures', ['fixture_date'], unique=False)
    op.create_table('freight_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('index_name', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('vessel_class_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vessel_class_id'], ['vessel_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_rates_index_name'), 'freight_rates', ['index_name'], unique=False)
    op.create_index(op.f('ix_freight_rates_rate_date'), 'freight_rates', ['rate_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freight_rates_rate_date'), table_name='freight_rates')
    op.drop_index(op.f('ix_freight_rates_index_name'), table_name='freight_rates')
    op.drop_table('freight_rates')
    op.drop_index(op.f('ix_fixtures_fixture_date'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('vessels')
    op.drop_table('trade_volumes')
    op.drop_table('routes')
    op.drop_table('berths')
    op.drop_table('vessel_classes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ports')
    op.drop_index(op.f('ix_disruption_events_start_date'), table_name='disruption_events')
    op.drop_table('disruption_events')
    # ### end Alembic commands ###
