"""haldia coal calls

Revision ID: d0708ec5c75a
Revises: f15254280991
Create Date: 2026-09-19 09:19:31.415288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0708ec5c75a'
down_revision: Union[str, Sequence[str], None] = 'f15254280991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haldia_coal_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.String(length=30), nullable=False),
    sa.Column('vessel_name', sa.String(length=80), nullable=False),
    sa.Column('first_report_date', sa.Date(), nullable=False),
    sa.Column('loa_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('expected_draft_m', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('cargo', sa.String(length=20), nullable=False),
    sa.Column('tonnage_t', sa.Integer(), nullable=True),
    sa.Column('importer_group', sa.String(length=20), nullable=False),
    sa.Column('origin_port', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vessel_id')
    )
    op.create_index(op.f('ix_haldia_coal_calls_first_report_date'), 'haldia_coal_calls', ['first_report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_haldia_coal_calls_first_report_date'), table_name='haldia_coal_calls')
    op.drop_table('haldia_coal_calls')
    # ### end Alembic commands ###
