"""port activity and chokepoint transits

Revision ID: f15254280991
Revises: 8cc68f1273fe
Create Date: 2026-09-18 22:05:03.144439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15254280991'
down_revision: Union[str, Sequence[str], None] = '8cc68f1273fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chokepoint_transits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chokepoint', sa.String(length=60), nullable=False),
    sa.Column('transit_date', sa.Date(), nullable=False),
    sa.Column('dry_bulk_transits', sa.Integer(), nullable=False),
    sa.Column('dry_bulk_capacity_dwt', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chokepoint', 'transit_date')
    )
    op.create_index(op.f('ix_chokepoint_transits_chokepoint'), 'chokepoint_transits', ['chokepoint'], unique=False)
    op.create_index(op.f('ix_chokepoint_transits_transit_date'), 'chokepoint_transits', ['transit_date'], unique=False)
    op.create_table('port_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_name', sa.String(length=80), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('dry_bulk_calls', sa.Integer(), nullable=False),
    sa.Column('dry_bulk_import_t', sa.Integer(), nullable=False),
    sa.Column('dry_bulk_export_t', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_name', 'activity_date')
    )
    op.create_index(op.f('ix_port_activity_activity_date'), 'port_activity', ['activity_date'], unique=False)
    op.create_index(op.f('ix_port_activity_port_name'), 'port_activity', ['port_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_port_activity_port_name'), table_name='port_activity')
    op.drop_index(op.f('ix_port_activity_activity_date'), table_name='port_activity')
    op.drop_table('port_activity')
    op.drop_index(op.f('ix_chokepoint_transits_transit_date'), table_name='chokepoint_transits')
    op.drop_index(op.f('ix_chokepoint_transits_chokepoint'), table_name='chokepoint_transits')
    op.drop_table('chokepoint_transits')
    # ### end Alembic commands ###
